# See: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

# Global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'webinar'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets/node/webinar-host01/alert.rules.yml"
  - "targets/node/webinar-host02/alert.rules.yml"
  - "targets/node/webinar-host03/alert.rules.yml"
  - "targets/node/webinar-host04/alert.rules.yml"
  - "targets/node/webinar-host05/alert.rules.yml"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'webinar-host01'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/node/webinar-host01/*.json'

  - job_name: 'webinar-host02'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/node/webinar-host02/*.json'

  - job_name: 'webinar-host03'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/node/webinar-host03/*.json'

  - job_name: 'webinar-host04'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/node/webinar-host04/*.json'
  - job_name: 'webinar-host05'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/node/webinar-host05/*.json'
